In [11]:
import pandas as pd
departments = {
    'Name': ["Ram", "Hari", "Sita"],
    'Age': [25,30,28],
    'Salary': [50000,60000,55000]

}
data = pd.DataFrame(departments)
# data['Age']
data[data["Salary"] > 55000]

   Name  Age  Salary
1  Hari   30   60000

In [ ]:
import pandas as pd
data =pd.read_csv("../data/names.csv")
# data.head()
data.describe()

            Age       Salary
count   5.000000      5.00000
mean   29.400000  57000.00000
std     3.646917   6082.76253
min    25.000000  50000.00000
25%    28.000000  52000.00000
50%    29.000000  58000.00000
75%    30.000000  60000.00000
max    35.000000  65000.00000

In [20]:
data.isnull().sum()

Name          0
Age           1
Salary        1
Department    1
dtype: int64